<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SlingNetwork\SlingNetwork.csproj" />
    <ProjectReference Include="..\..\src\SlingNetwork.UI\SlingNetwork.UI.csproj" />
  </ItemGroup>

</Project>
