Command.DefaultHandler.Description = "Sling is a P2P punch networking tool. The name Sling is derived from 'sling': when a device cannot directly connect to a target, it attempts to throw a connection sling to hook both parties into the same network link."
Command.DefaultHandler.Foo = "Sample option"
Command.ServeHandler.Description = "Start the control service, which provides HTTP services for offering P2P punch information to clients, NAT type detection, and can also act as a backup server for other control servers."
Command.ServeHandler.ControlListenEndPoints = "IP:Port that the control service listens on. Multiple can be specified, defaults include 0.0.0.0:80 and [::]:80."
Command.ServeHandler.AdminListenEndPoints = "IP:Port that the admin service listens on. Multiple can be specified, defaults include 0.0.0.0:81 and [::]:81."
Command.ServeHandler.PartnerControlUrls = "URLs (http) that the partner control service listens on, e.g. https://ipv4.example.com,https://ipv6.example.com. When a client wishes to perform a NAT test, all these URLs are returned, and the client can choose which partner server to use based on its needs."
Command.ServeHandler.UdpHosts = "List of hostnames used by the UDP service externally. Multiple can be specified when the IPv4 and IPv6 domain names differ. When not specified, the client will attempt to use the control server's domain name."
Command.ServeHandler.UdpPortRange = "UDP listening port or port range. Default is 50000, can also be specified as 50000-50999 (both ends inclusive); the control service returns the actually available UDP port to the client for punching, NAT type detection, and other purposes."
Command.ConnectHandler.Description = "As a P2P punch client, connect to a control server to complete punching."
Command.ConnectHandler.ControlUrl = "Specify which control server to connect to, to assist this client in completing P2P punching tasks."
Command.ConnectHandler.PeerName = "Specifies the suggested display name for this client. Other clients identify this client by its public key; when no custom name is set, this name can be displayed."
Command.NatTestHandler.Description = "Perform a NAT type detection using the specified control server."
Command.NatTestHandler.ControlUrl = "Specify which control server to connect to, to assist this client in completing NAT type detection tasks."
Command.NatTestHandler.PacketRepeatCount = "How many times each UDP packet is sent repeatedly (in poor network conditions, a higher value can be used; default is 1)."
Command.NatTestHandler.PacketRepeatDelay = "The delay between retransmissions when UDP packets need to be resent (in ms; default is 500ms)."
Command.NatTestHandler.Verbose = "Output a detailed NAT test report instead of just the NAT type conclusion."
Command.ParseValueException.IPEndPoint = "The specified value \"{value:string}\" is not a valid IP:Port format."
Command.ParseValueException.PortRange = "The specified value \"{value:string}\" is not a valid port or port range. Valid format examples: 1000 or 1000-1999 (both ends inclusive)."
Command.ParseValueException.Url = "The specified value \"{value:string}\" is not a valid URL."
NatTest.Report.Title = "NAT test result:"
NatTest.Report.Success = "Success"
NatTest.Report.SessionId = "Session ID"
NatTest.Report.Mapping = "Mapping behavior (RFC 5780)"
NatTest.Report.Filtering = "Filtering behavior (RFC 5780)"
NatTest.Report.LegacyNatType = "Legacy NAT type (RFC 3489, obsolete)"
NatTest.Report.ClientLocalEndPoint = "Local endpoint"
NatTest.Report.ClientPublicEndPoint1 = "Public endpoint (  first    test)"
NatTest.Report.ClientPublicEndPoint2 = "Public endpoint (address changed)"
NatTest.Report.ClientPublicEndPoint3 = "Public endpoint (   port changed)"
NatTest.Report.IsPublicEndPoint = "Is public endpoint"
NatTest.Report.NotTested = "Not tested"
Enums.NatMappingBehavior.EndpointIndependent = "Endpoint Independent"
Enums.NatMappingBehavior.AddressDependent = "Address Dependent"
Enums.NatMappingBehavior.AddressAndPortDependent = "Address and Port Dependent"
Enums.NetworkPacketFilteringBehavior.EndpointIndependent = "Endpoint Independent"
Enums.NetworkPacketFilteringBehavior.AddressDependent = "Address Dependent"
Enums.NetworkPacketFilteringBehavior.AddressAndPortDependent = "Address and Port Dependent"
Enums.Rfc3489NatType.NotRepresentable = "Not representable by legacy classification"
Enums.Rfc3489NatType.FullCone = "Full cone"
Enums.Rfc3489NatType.RestrictedCone = "Address restricted cone"
Enums.Rfc3489NatType.PortRestrictedCone = "Port restricted cone"
Enums.Rfc3489NatType.Symmetric = "Symmetric"
Values.Boolean.True = "Yes"
Values.Boolean.False = "No"
