Command.DefaultHandler.Description = "Sling 是一个 P2P 打洞组网工具。名称 Sling 取自“吊索”：当设备无法直接连接目标时，尝试抛出一条连接吊索，将双方挂接到同一条网络链路中。"
Command.DefaultHandler.Foo = "示例选项"
Command.ServeHandler.Description = "启动控制服务，提供 http 服务用于提供客户端 P2P 打洞信息、提供 NAT 类型检测等，也可以成为其他控制服务器的备用服务器。"
Command.ServeHandler.ControlListenEndPoints = "控制服务监听的 IP:Port。可指定多个，默认包含 0.0.0.0:80 和 [::]:80。"
Command.ServeHandler.AdminListenEndPoints = "管理服务监听的 IP:Port。可指定多个，默认包含 0.0.0.0:81 和 [::]:81。"
Command.ServeHandler.PartnerControlUrls = "备用服务监听的 URL（http），https://ipv4.example.com,https://ipv6.example.com。当客户端希望进行 NAT 测试时，会返回所有这些 URL，客户端自己根据需求选择希望使用的备用服务器。"
Command.ServeHandler.UdpHosts = "UDP 服务对外使用的主机名列表。当 IPv4 和 IPv6 域名不同时，可指定多个。不指定时，客户端将尝试使用控制服务器的域名。"
Command.ServeHandler.UdpPortRange = "UDP 监听端口或端口范围。默认为 50000，也可指定为 50000-50999（两端包含）；控制服务会向客户端返回实际可用的 UDP 端口，用于打洞、NAT 类型探测等用途。"
Command.ConnectHandler.Description = "作为 P2P 打洞客户端，连接一个控制服务器以完成打洞。"
Command.ConnectHandler.ControlUrl = "指定要连接哪一个控制服务器，辅助本客户端完成 P2P 打洞或 NAT 类型探测等任务。"
Command.ConnectHandler.PeerName = "指定本客户端的建议显示名称。其他客户端使用本客户端的公钥识别身份；在没有自定义名称时，可显示此名称。"
Command.ParseValueException.IPEndPoint = "指定的值“{value:string}”不是有效的 IP:Port 格式。"
Command.ParseValueException.PortRange = "指定的值“{value:string}”不是有效的端口或端口范围。有效格式示例：1000 或 1000-1999（两端包含）。"
Command.ParseValueException.Url = "指定的值“{value:string}”不是有效的 URL。"
